# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  docker_registry: 'ericuss'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      displayName: Docker compose build
      inputs:
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        includeSourceTags: true
        dockerComposeFileArgs: 'DOCKER_REGISTRY=$(docker_registry)/'
    
    # - task: DockerCompose@0
    #   displayName: Docker compose publish
    #   inputs:
    #     containerregistrytype: 'Azure Container Registry'
    #     azureSubscription: $(azureSubscriptionEndpoint)
    #     azureContainerRegistry: '{"loginServer":"$(azureContainerRegistryLogin)", "id" : "$(azureContainerRegistryId)"}'
    #     dockerComposeFile: '**/docker-compose.yml'
    #     action: 'Push services'
    #     additionalImageTags: '$(Build.BuildId)'
    #     dockerComposeFileArgs: 'DOCKER_REGISTRY=$(azureContainerRegistryLogin)/'

