version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5280:80"
      - "52443:443"
      
  shop-vue:
    environment:
      - VUE_APP_BFF_URL=http://host.docker.internal:4080
    ports:
      - "3080:8080"
  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecks-UI__HealthChecks__0__Uri=http://host.docker.internal:5080/hc
      - HealthChecks-UI__HealthChecks__1__Uri=http://host.docker.internal:4080/hc
      - HealthChecks-UI__HealthChecks__2__Uri=http://host.docker.internal:1080/hc
      - HealthChecks-UI__HealthChecks__3__Uri=http://host.docker.internal:5380/hc
      - HealthChecks-UI__HealthChecks__4__Uri=http://host.docker.internal:5480/hc
    ports:
      - "5080:80"
      - "50443:443"
  bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Apis__0__Uri=http://host.docker.internal:5380
      - Apis__1__Uri=http://host.docker.internal:5480
    ports:
      - "4080:80"
      - "40443:443"
  api-products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=53443
      - https_port=53443
      - Kestrel__EndPoints__Http__Url=http://+:80
      - Kestrel__EndPoints__Https__Url=https://+:443
      - Kestrel__Certificates__Default__Path=cert.pfx
      - Kestrel__Certificates__Default__Password=Pass@word
    ports:
      - "5380:80"
      - "53443:443"
  api-stock:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5480:80"
      - "54443:443"
  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1080:80"
      - "10443:443"