apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl
            image: ericuss/etl:latest
          restartPolicy: OnFailure