apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webstatus
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webstatus
    spec:
      containers:
        - name: webstatus
          image: ericuss/webstatus:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webstatus
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webstatus
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: webstatus
# spec:
#   type: ExternalName
#   externalName: webstatus.svc.cluster.local
#   ports:
#   - port: 80



# apiVersion: v1
# kind: Service
# metadata:
#     name: webstatus
# spec:
#   ports:
#     - name: http-port
#       port: 80
#       targetPort: 80
#   selector:
#     app: webstatus
#   type: LoadBalancer
#   apiVersion: v1