# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  docker_registry: 'ericuss'
  container_registry_connection: 'docker ericuss'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      displayName: Docker compose build
      inputs:
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        includeSourceTags: true
        dockerComposeFileArgs: 'DOCKER_REGISTRY=$(docker_registry)/'
    - task: Docker@2
      inputs:
        containerRegistry: '$(container_registry_connection)'
        command: 'login'
        
    - task: DockerCompose@0
      displayName: Docker compose publish
      inputs:
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        additionalImageTags: '$(Build.BuildId)'
        dockerComposeFileArgs: 'DOCKER_REGISTRY=$(docker_registry)/'
- stage: Deploy
  displayName: Deploy arm
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Lanre MSDN'
        subscriptionId: '484614b5-be32-42e5-b226-fbba74cadb9a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Lanre'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'deploy/classic/template.json'
        csmParametersFile: 'deploy/classic/parameters.json'
        overrideParameters: '-dockerRegistryUsername $(docker_registry_username) -dockerRegistryPassword $(docker_registry_password)'
        deploymentMode: 'Incremental'
        deploymentName: 'product-api-deploy'

