name: Docker compose build webstatus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose build webstatus
